"""Root-level Vercel deployment file generator (project-root helper).

This workspace can only write files inside the ``app/`` package, but Vercel
reads the serverless function entrypoint and its configuration only from the
**project root** — in this workspace that is the current working directory,
the one containing ``rxconfig.py``.

Run this helper from the project root::

    python -m app.vercel_setup            # add --force to overwrite

It resolves the project root from ``Path.cwd()`` (walking up until it finds
``rxconfig.py``) — never relative to the ``app`` package — and writes:

- ``<project root>/api/index.py`` — a copy of ``app/api/index.py``, the
  canonical entrypoint source, which imports the resolved ASGI application
  from ``app.vercel_asgi`` and exposes it as both ``app`` and ``handler``.
- ``<project root>/vercel.json`` — builds ``api/index.py`` with
  ``@vercel/python`` on a supported Python runtime and rewrites every path to
  that function.

Nothing about the app itself (UI, routes, state, Supabase, Google OAuth or the
messenger behavior) is touched. Existing root files are left alone unless
``--force`` is passed.
"""

import argparse
import logging
import sys
from pathlib import Path

API_INDEX_SOURCE = '''"""Vercel serverless function entrypoint.

Vercel's Python runtime imports this module and serves its module-level ``app``
object as an ASGI application. The resolution work lives in
``app/vercel_asgi.py``, which imports the existing Reflex application and
extracts its underlying ASGI callable in a version-tolerant way.

This file only makes the project root importable and re-exports that ASGI
app as both ``app`` and ``handler``. No app behavior is changed here.

Generated by ``python -m app.vercel_setup``.
"""

import sys
from pathlib import Path


def _project_root() -> Path:
    """Locate the project root (the nearest parent holding ``rxconfig.py``)."""
    here = Path(__file__).resolve()
    for candidate in here.parents:
        if (candidate / "rxconfig.py").exists():
            return candidate
    for candidate in here.parents:
        if (candidate / "app" / "vercel_asgi.py").exists():
            return candidate
    return here.parent.parent


_ROOT = str(_project_root())
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from app.vercel_asgi import app, handler  # noqa: E402,F401

__all__ = ["app", "handler"]
'''

VERCEL_JSON_SOURCE = """{
  "version": 2,
  "builds": [
    {
      "src": "api/index.py",
      "use": "@vercel/python",
      "config": {
        "runtime": "python3.12",
        "maxLambdaSize": "50mb"
      }
    }
  ],
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/api/index.py"
    }
  ]
}
"""


def project_root(start: Path | None = None) -> Path:
    """Return the project root: the nearest directory holding ``rxconfig.py``.

    Resolution is anchored on the current working directory (or ``start``),
    NOT on the location of the ``app`` package, so running the helper from the
    workspace root writes ``./api/index.py`` and ``./vercel.json`` there.
    Parent directories are searched as a convenience when the helper is run
    from a subdirectory, and the package parent is only a last-resort
    fallback.
    """
    base = (start or Path.cwd()).resolve()
    for candidate in (base, *base.parents):
        if (candidate / "rxconfig.py").exists():
            return candidate
    package_parent = Path(__file__).resolve().parent.parent
    if (package_parent / "rxconfig.py").exists():
        return package_parent
    return base


# Backwards-compatible alias for earlier callers/documentation.
repository_root = project_root


def entrypoint_source() -> str:
    """Return the entrypoint code, preferring the canonical ``app/api/index.py``."""
    canonical = Path(__file__).resolve().parent / "api" / "index.py"
    try:
        if canonical.exists():
            content = canonical.read_text()
            if "app.vercel_asgi" in content:
                return content
            logging.warning(
                f"{canonical} does not import app.vercel_asgi; "
                "falling back to the embedded entrypoint source."
            )
    except OSError as e:
        logging.exception(f"Error reading {canonical}: {e}")
    return API_INDEX_SOURCE


def _write(path: Path, content: str, force: bool) -> str:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and not force:
            if path.read_text() == content:
                return f"unchanged: {path}"
            return f"skipped (exists, use --force): {path}"
        path.write_text(content)
        return f"wrote: {path}"
    except OSError as e:
        logging.exception(f"Error writing {path}: {e}")
        return f"failed: {path} ({e})"


def generate(force: bool = False, root: Path | None = None) -> list[str]:
    """Create ``api/index.py`` and ``vercel.json`` at the project root."""
    target = root.resolve() if root is not None else project_root()
    return [
        f"project root: {target}",
        _write(target / "api" / "index.py", entrypoint_source(), force),
        _write(target / "vercel.json", VERCEL_JSON_SOURCE, force),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Write api/index.py and vercel.json to the project root "
            "(the current directory containing rxconfig.py)."
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing root api/index.py and vercel.json.",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Explicit project root (defaults to the detected cwd root).",
    )
    args = parser.parse_args()
    results = generate(
        force=args.force,
        root=Path(args.root) if args.root else None,
    )
    for line in results:
        print(line)
    return 1 if any(line.startswith("failed") for line in results) else 0


if __name__ == "__main__":
    sys.exit(main())
